[template]
  incoming-hooks = ["Directus"]
[template.environment]
  DEVCYCLE_CLIENT_KEY = "Change me to your DevCycle Projects Client SDK Key"
  DIRECTUS_API_URL = "Change me to the API url for your Directus Instance"